name: Configure Branch Protection Rules
on:
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pull-requests: read
      
    steps:
      - name: Protect main branch (only from release/*)
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1,
                "require_code_owner_reviews": false
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'

      - name: Restrict merges to main (only release/* PRs)
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json;application/vnd.github+mercy-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/rulesets \
            -d '{
              "name": "Only release branches can merge into main",
              "target": "branch",
              "enforcement": "active",
              "conditions": {
                "ref_name": {
                  "include": ["main"],
                  "exclude": []
                }
              },
              "rules": [
                {
                  "type": "pull_request",
                  "parameters": {
                    "required_approving_review_count": 1,
                    "dismiss_stale_reviews_on_push": true,
                    "require_code_owner_review": false,
                    "restrict_source_branches": {
                      "include": ["release/**"],
                      "exclude": []
                    },
                    "require_last_push_approval": false
                  }
                }
              ]
            }'

      - name: Protect develop branch (only via PR)
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/branches/develop/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": []
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "required_approving_review_count": 1
              },
              "restrictions": null,
              "allow_force_pushes": false,
              "allow_deletions": false
            }'
